enableTelemetry: false

nodeLinker: node-modules

packageExtensions:
  http-proxy-middleware@^2.0.0:
    dependencies:
      "@types/express": ^4.17.13

yarnPath: .yarn/releases/yarn-3.1.0.cjs
ignorePath: false
